### ISSUE TITLE
ValueError error with a random show

### ISSUE THREAD

**Issue by aaomidi** [oseiskar/autosubsync#3]
Error with a random show I have

```
ValueError: invalid literal for int() with base 10: b'"\xc8\xd1\xc7\xed \xd3\xe1\xc7\xe3\xca\xed \xd4\xc7\xe5 "\xd1\xc7\xc8\xd1\xca'
```

Looks like this error was related to the subtitle. Probably just encoding a weird character. Something larger than 32 bits maybe?

**Comment by oseiskar** [comment]
Are you sure your command line arguments are in the correct order? For example

    autosubsync movie.mkv unsyncedsubs.srt output.srt

I just checked that you get that error if you accidentally give a video file (or other non-SRT file) as subtitle file parameters, e.g., `autosubsync subs.srt movie.mkv out.srt`.

I'll add a better error message to handle this case.

Weird characters should be supported since the SRT files are essentially handled as "binary" to support all possible encodings.

**Comment by aaomidi** [comment]
Yeah I've been using this and I'm planning a port of this to plex.

Looks like the issue was that sometimes the persian subtitles mess stuff up. I'll confirm once more!

**Comment by oseiskar** [comment]
Ok. If you have an example of an SRT file that does not work but still displays in some video player, could you send that (or a part of that) to me and I'll try to fix? The idea with the [custom SRT parsing](https://github.com/oseiskar/autosubsync/blob/master/autosubsync/srt_io.py) was to get this to work with practically any language and encoding, but I haven't tested with too many subtitle languages. 

I initially tried using a library (PySrt if I recall correctly) but it had trouble parsing some subtitles. Could also try another one like https://pypi.org/project/srt/

**Comment by aaomidi** [comment]
Hey! Here's the subtitle.

*(EDIT: removed by @oseiskar)*

After using this utility on it, https://github.com/hamidrezakp/SubFixer the program works as expected.

I should also thank you for this. Its an amazing project.

**Comment by oseiskar** [comment]
Thanks! Great that you found the project useful.

It turned out that the problem was not really the Persian language (with lots of multi-byte sequences), but double line breaks within the text. Something like this:
```
1
00:07:44,300 --> 00:07:50,500
Valid subtitle
with two lines

2
00:07:50,511 --> 00:07:53,922

Double line break above ^^, not OK

3
00:07:56,544 --> 00:07:59,918
More subtitles
...
```
I'm not sure if double line breaks are technically valid SRT or not but added support for that anyway in #5. I also removed the original subtitle file, since I'm not sure if Github likes hosting subtitle files here in the long term.

**Comment by aaomidi** [comment]
Thanks!
